name: CI
on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: guardian/actions-setup-node@v2.4.0
      - uses: bahmutov/npm-install@v1
      - run: yarn lint
